import React from 'react';
import { CheckCircle2, Copy, Printer, X, Scale, FileText } from 'lucide-react';
import { ClinicSettings, Settlement } from '../types';

interface SettlementReceiptModalProps {
  settlement: Settlement | null;
  settings: ClinicSettings;
  onClose: () => void;
  showToast: (title: string, desc?: string, type?: 'success' | 'info' | 'warning' | 'error') => void;
}

export const SettlementReceiptModal: React.FC<SettlementReceiptModalProps> = ({
  settlement,
  settings,
  onClose,
  showToast,
}) => {
  if (!settlement) return null;

  const currency = settings.currencySymbol || '৳';
  const formatNumber = (num: number) => new Intl.NumberFormat('en-BD').format(Math.round(num));

  const handleCopySummary = () => {
    const text = `
DENTAL CLINIC SETTLEMENT RECEIPT
--------------------------------------
Settlement ID: ${settlement.settlementId}
Date: ${settlement.settlementDate}
Clinic: ${settings.clinicName}
Doctor: ${settings.doctorName}
Period: ${settlement.periodFrom} to ${settlement.periodTo}
Patients Settled: ${settlement.patientCount}

FINANCIAL BREAKDOWN:
- Period 40% Share: ${currency} ${formatNumber(settlement.periodShare)}
- Carried-over Arrears: ${currency} ${formatNumber(settlement.previousDue)}
- Total Payable: ${currency} ${formatNumber(settlement.totalPayable)}
- Amount Paid by Clinic: ${currency} ${formatNumber(settlement.amountReceived)}
- Due Carried Forward: ${currency} ${formatNumber(settlement.dueBalance)}
${settlement.remarks ? `Notes: ${settlement.remarks}` : ''}
--------------------------------------
Generated by Hisapp
    `.trim();

    navigator.clipboard.writeText(text);
    showToast('Copied to Clipboard', 'Settlement summary copied to clipboard', 'success');
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm animate-in fade-in">
      <div className="ios-glass bg-white/95 rounded-3xl p-6 w-full max-w-md shadow-2xl space-y-5">
        <div className="flex items-center justify-between pb-3 border-b border-slate-100">
          <div className="flex items-center gap-2 text-emerald-600">
            <CheckCircle2 className="w-5 h-5" />
            <h3 className="text-base font-bold text-slate-900">Settlement Finalized</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-full text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Digital Receipt Card */}
        <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-4 font-sans text-xs">
          <div className="text-center pb-3 border-b border-dashed border-slate-300 flex flex-col items-center">
            {settings.clinicLogo && (
              <img
                src={settings.clinicLogo}
                alt={settings.clinicName || 'Clinic Logo'}
                className="w-10 h-10 object-contain mb-1.5 rounded-lg"
                onError={(e) => {
                  (e.currentTarget as HTMLElement).style.display = 'none';
                }}
              />
            )}
            <span className="text-[10px] uppercase font-bold text-indigo-600 tracking-wider">
              {settings.clinicName || 'Yashfin Dental Care'}
            </span>
            <h4 className="text-base font-black text-slate-900 mt-0.5">
              Clinical Payout Settlement
            </h4>
            <div className="font-mono text-xs font-bold text-slate-500 mt-1">
              {settlement.settlementId}
            </div>
          </div>

          <div className="space-y-2">
            <div className="flex justify-between text-slate-600">
              <span>Doctor:</span>
              <span className="font-semibold text-slate-900">{settings.doctorName}</span>
            </div>
            <div className="flex justify-between text-slate-600">
              <span>Date Range:</span>
              <span className="font-medium text-slate-800">
                {settlement.periodFrom} ~ {settlement.periodTo}
              </span>
            </div>
            <div className="flex justify-between text-slate-600">
              <span>Patients Count:</span>
              <span className="font-semibold text-slate-900">{settlement.patientCount} visits</span>
            </div>
          </div>

          <div className="pt-2 border-t border-slate-200 space-y-2">
            <div className="flex justify-between text-slate-600">
              <span>Period Doctor Share (40%):</span>
              <span className="font-bold text-slate-800">
                {currency} {formatNumber(settlement.periodShare)}
              </span>
            </div>
            <div className="flex justify-between text-slate-600">
              <span>Carried-over Arrears:</span>
              <span className="font-semibold text-amber-700">
                {currency} {formatNumber(settlement.previousDue)}
              </span>
            </div>
            <div className="flex justify-between font-bold text-slate-900 pt-1 border-t border-slate-200">
              <span>Total Payable:</span>
              <span className="text-indigo-600 font-black">
                {currency} {formatNumber(settlement.totalPayable)}
              </span>
            </div>
            <div className="flex justify-between text-slate-600">
              <span>Amount Received:</span>
              <span className="font-bold text-emerald-600">
                {currency} {formatNumber(settlement.amountReceived)}
              </span>
            </div>
            <div className="flex justify-between font-black text-slate-900 pt-1 border-t border-slate-300">
              <span>Next Carry-Forward Due:</span>
              <span
                className={`${
                  settlement.dueBalance > 0 ? 'text-amber-600' : 'text-slate-800'
                }`}
              >
                {currency} {formatNumber(settlement.dueBalance)}
              </span>
            </div>
          </div>

          {settlement.remarks && (
            <div className="pt-2 border-t border-dashed border-slate-300 text-slate-500 italic">
              Note: {settlement.remarks}
            </div>
          )}
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopySummary}
            className="flex-1 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold flex items-center justify-center gap-1.5 transition active:scale-95"
          >
            <Copy className="w-3.5 h-3.5" />
            <span>Copy Receipt</span>
          </button>
          <button
            onClick={onClose}
            className="flex-1 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold transition active:scale-95"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
};
